application: stage-5-1044
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /$
  static_files: Stage_5.html
  upload: Stage_5.html

libraries:
- name: webapp2
  version: "2.5.2"
